monitor.bluez.properties = {
  bluez5.roles = [ a2dp_source ]
  bluez5.auto-connect = [ a2dp_source ]
}
wireplumber.settings = {
  bluetooth.autoswitch-to-headset-profile = false
  device.restore-profile = false
}
