monitor.bluez.properties = {
  bluez5.enable-hw-volume = true
}

monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "~bluez_card.*"
      }
    ]
    actions = {
      update-props = {
        bluez5.hw-volume = [ a2dp_sink a2dp_source hfp_hf hsp_hs hfp_ag hsp_ag ]
      }
    }
  }
]
