#!/usr/bin/env bash
set -uo pipefail

INSTALLER_PATH="$HOME/.local/bin/install-omarchy-heroic-theme-sync.sh"
HOOK_DIR="$HOME/.config/omarchy/hooks/theme-set.d"
HOOK_PATH="$HOOK_DIR/sync-heroic"
OMARCHY_THEME_DIR="$HOME/.config/omarchy/current/theme"
OMARCHY_COLORS_FILE="$OMARCHY_THEME_DIR/colors.toml"
OMARCHY_THEME_NAME_FILE="$HOME/.config/omarchy/current/theme.name"
HEROIC_CONFIG_DIR="${HEROIC_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/heroic}"
HEROIC_STORE_DIR="$HEROIC_CONFIG_DIR/store"
HEROIC_APP_CONFIG_PATH="$HEROIC_CONFIG_DIR/config.json"
HEROIC_STORE_CONFIG_PATH="$HEROIC_STORE_DIR/config.json"
HEROIC_THEMES_DIR="${HEROIC_THEMES_DIR:-$HEROIC_CONFIG_DIR/themes}"
HEROIC_THEME_NAME="omarchy.css"
HEROIC_THEME_PATH="$HEROIC_THEMES_DIR/$HEROIC_THEME_NAME"

log() {
  printf 'omarchy-heroic-theme-sync: %s\n' "$*" >&2
}

usage() {
  cat <<'USAGE'
Usage:
  install-omarchy-heroic-theme-sync.sh          Install the Omarchy hook and sync Heroic now
  install-omarchy-heroic-theme-sync.sh --sync   Sync Heroic with the current Omarchy theme now

The hook runs after `omarchy theme set ...`, generates
~/.config/heroic/themes/omarchy.css from the active Omarchy colors.toml,
sets Heroic's customThemesPath to ~/.config/heroic/themes, and selects
omarchy.css as Heroic's current theme.

Set HEROIC_CONFIG_DIR before running if your Heroic config directory is not
~/.config/heroic. Set HEROIC_THEMES_DIR to place generated CSS elsewhere.
USAGE
}

sync_heroic() {
  if [[ ! -f "$OMARCHY_COLORS_FILE" ]]; then
    log "No Omarchy colors file found at $OMARCHY_COLORS_FILE"
    return 0
  fi

  if ! command -v python3 >/dev/null; then
    log "python3 is required to generate Heroic's CSS theme"
    return 1
  fi

  mkdir -p "$HEROIC_THEMES_DIR" "$HEROIC_STORE_DIR"

  python3 - "$OMARCHY_COLORS_FILE" "$OMARCHY_THEME_DIR" "$OMARCHY_THEME_NAME_FILE" "$HEROIC_THEME_PATH" "$HEROIC_APP_CONFIG_PATH" "$HEROIC_STORE_CONFIG_PATH" "$HEROIC_THEMES_DIR" "$HEROIC_THEME_NAME" <<'PYTHON'
import json
import re
import shutil
import sys
from pathlib import Path

colors_path = Path(sys.argv[1])
theme_dir = Path(sys.argv[2])
theme_name_path = Path(sys.argv[3])
theme_path = Path(sys.argv[4])
app_config_path = Path(sys.argv[5])
store_config_path = Path(sys.argv[6])
themes_dir = Path(sys.argv[7])
theme_name = sys.argv[8]

HEX_RE = re.compile(r"^#[0-9a-fA-F]{6}$")


def read_colors(path):
    colors = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if value.startswith(("\"", "'")):
            quote = value[0]
            value = value[1:].split(quote, 1)[0]
        else:
            value = value.split("#", 1)[0].strip()
        if HEX_RE.match(value):
            colors[key] = value.upper()
    return colors


def color(colors, key, fallback):
    value = colors.get(key, fallback)
    return value.upper() if HEX_RE.match(value) else fallback.upper()


def rgb(hex_color):
    hex_color = hex_color.lstrip("#")
    return tuple(int(hex_color[i : i + 2], 16) for i in (0, 2, 4))


def hex_from_rgb(values):
    return "#" + "".join(f"{max(0, min(255, round(v))):02X}" for v in values)


def mix(a, b, amount):
    ar, ag, ab = rgb(a)
    br, bg, bb = rgb(b)
    return hex_from_rgb((
        ar + (br - ar) * amount,
        ag + (bg - ag) * amount,
        ab + (bb - ab) * amount,
    ))


def alpha(hex_color, opacity):
    return f"color-mix(in srgb, {hex_color} {opacity}%, transparent)"


def read_config(path):
    if not path.exists():
        return {}
    raw = path.read_text().strip()
    return json.loads(raw) if raw else {}


colors = read_colors(colors_path)
is_light = (theme_dir / "light.mode").exists()
omarchy_theme_name = theme_name_path.read_text().strip() if theme_name_path.exists() else "unknown"

bg = color(colors, "background", "#FAFAFA" if is_light else "#111111")
fg = color(colors, "foreground", "#1A1A1A" if is_light else "#EEEEEE")
accent = color(colors, "accent", color(colors, "color4", "#1DE8F5"))
cursor = color(colors, "cursor", fg)
selection_bg = color(colors, "selection_background", mix(bg, accent, 0.35))
selection_fg = color(colors, "selection_foreground", fg)

red = color(colors, "color1", "#F97881")
green = color(colors, "color2", "#0CE396")
yellow = color(colors, "color3", "#F8AE79")
blue = color(colors, "color4", accent)
magenta = color(colors, "color5", accent)
cyan = color(colors, "color6", accent)
muted = color(colors, "color8", mix(bg, fg, 0.50))

surface_0 = mix(bg, fg, 0.06)
surface_1 = mix(bg, fg, 0.11)
surface_2 = mix(bg, fg, 0.18)
surface_3 = mix(bg, fg, 0.32)
hover = mix(bg, accent, 0.22)
hover_strong = mix(bg, accent, 0.38)

css = f"""/*
 * Auto-generated by install-omarchy-heroic-theme-sync.sh.
 * Source Omarchy theme: {omarchy_theme_name}
 */
body.omarchy,
body.omarchy_css {{
  --brand-primary: {accent};
  --brand-primary-hover: {mix(accent, fg, 0.22)};
  --brand-secondary: {magenta};
  --brand-secondary-hover: {mix(magenta, fg, 0.22)};
  --brand-text-01: {fg};
  --brand-text-02: {mix(fg, accent, 0.18)};
  --brand-text-03: {mix(fg, bg, 0.28)};
  --brand-text-04: {selection_fg};
  --brand-text-05: {muted};
  --neutral-01: {mix(bg, "#000000", 0.18)};
  --neutral-02: {surface_0};
  --neutral-03: {surface_1};
  --neutral-04: {surface_2};
  --neutral-05: {surface_3};
  --neutral-06: {mix(fg, bg, 0.18)};
  --neutral-07: {mix(fg, bg, 0.08)};
  --neutral-08: {fg};
  --status-default: {muted};
  --status-success: {green};
  --status-warning: {yellow};
  --status-danger: {red};
  --status-info: {cyan};
  --status-default-hover: {mix(muted, fg, 0.20)};
  --status-success-hover: {mix(green, fg, 0.18)};
  --status-warning-hover: {mix(yellow, fg, 0.18)};
  --status-danger-hover: {mix(red, fg, 0.18)};
  --status-info-hover: {mix(cyan, fg, 0.18)};
  --accent: {accent};
  --accent-02: {alpha(accent, 35)};
  --accent-overlay: {hover_strong};
  --primary-hover: {mix(accent, bg, 0.22)};
  --primary-active: {mix(accent, fg, 0.35)};
  --secondary-hover: {hover};
  --secondary-active: {blue};
  --base-06: {muted};
  --text-default: {fg};
  --text-secondary: {mix(fg, bg, 0.22)};
  --text-tertiary: {bg if is_light else mix(bg, "#000000", 0.10)};
  --text-quartenary: {muted};
  --text-hover: {mix(fg, accent, 0.20)};
  --background: {surface_0};
  --background-darker: {bg};
  --background-lighter: {surface_1};
  --body-background: {bg};
  --input-background: {surface_1};
  --current-background: {bg};
  --modal-background: {bg};
  --modal-border: {surface_2};
  --modal-backdrop: color-mix(in srgb, {bg} 84%, transparent);
  --navbar-background: {surface_0};
  --navbar-active: {fg};
  --navbar-inactive: {muted};
  --navbar-active-background: {hover};
  --navbar-accent: {fg};
  --divider: {surface_2};
  --icons-background: {surface_0};
  --icon-disabled: {surface_2};
  --icon-disabled-overlay: {surface_3};
  --action-icon: {muted};
  --action-icon-hover: {fg};
  --action-icon-active: {accent};
  --primary-button: {accent};
  --secondary-button: {blue};
  --button-stroke: {selection_bg};
  --secondary-button-overlay: {hover_strong};
  --tertiary-button-overlay: {surface_2};
  --disabled-button: {surface_1};
  --disabled-button-overlay: {surface_3};
  --play-button: {accent};
  --install-button: {blue};
  --cancel-button: {yellow};
  --cancel-button-overlay: {mix(yellow, fg, 0.18)};
  --success-button: {green};
  --link-highlight: {accent};
  --success: {green};
  --success-hover: {mix(green, fg, 0.18)};
  --danger: {red};
  --danger-hover: {mix(red, fg, 0.18)};
  --primary: {accent};
  --search-bar-background: {surface_0};
  --search-bar-border: {surface_2};
  --osk-background: {bg};
  --osk-button-background: {surface_1};
  --osk-button-border: {surface_2};
  --controller-hints-background: transparent;
  --gamecard-title-color: color-mix(in srgb, {bg} 82%, transparent);
  --gradient-body-background: linear-gradient(90deg, {mix(bg, "#000000", 0.12)} -32px, {bg} 64px, {bg} 100%);
  --gradient-gamecard: linear-gradient(180deg, transparent 0%, var(--gamecard-title-color) 48%);
  caret-color: {cursor};
}}

body.omarchy ::selection,
body.omarchy_css ::selection {{
  background: {selection_bg};
  color: {selection_fg};
}}
"""

theme_path.write_text(css)

app_config_path.parent.mkdir(parents=True, exist_ok=True)
app_config = read_config(app_config_path)
if app_config_path.exists():
    backup_path = app_config_path.with_name(app_config_path.name + ".pre-omarchy-heroic-theme-sync")
    if not backup_path.exists():
        shutil.copy2(app_config_path, backup_path)

default_settings = app_config.setdefault("defaultSettings", {})
default_settings["customThemesPath"] = str(themes_dir)
if str(default_settings.get("customCSS", "")).startswith("/*\n * Auto-generated by install-omarchy-heroic-theme-sync.sh."):
    default_settings.pop("customCSS", None)
app_config.setdefault("version", "v0")
app_config_path.write_text(json.dumps(app_config, indent="\t") + "\n")

store_config_path.parent.mkdir(parents=True, exist_ok=True)
store_config = read_config(store_config_path)
if store_config_path.exists():
    backup_path = store_config_path.with_name(store_config_path.name + ".pre-omarchy-heroic-theme-sync")
    if not backup_path.exists():
        shutil.copy2(store_config_path, backup_path)

store_config["theme"] = theme_name
store_config_path.write_text(json.dumps(store_config, indent="\t") + "\n")
PYTHON

  log "Generated $HEROIC_THEME_PATH."
  log "Wrote customThemesPath to $HEROIC_APP_CONFIG_PATH and selected $HEROIC_THEME_NAME in $HEROIC_STORE_CONFIG_PATH."
  log "Restart Heroic if it is already open."
}

install_hook() {
  local source_path target_path

  mkdir -p "$HOME/.local/bin" "$HOOK_DIR"

  source_path=$(realpath -m "${BASH_SOURCE[0]}")
  target_path=$(realpath -m "$INSTALLER_PATH")
  if [[ "$source_path" != "$target_path" ]]; then
    cp "$source_path" "$INSTALLER_PATH"
  fi
  chmod +x "$INSTALLER_PATH"

  cat >"$HOOK_PATH" <<'HOOK'
#!/usr/bin/env bash
exec "$HOME/.local/bin/install-omarchy-heroic-theme-sync.sh" --sync "$@"
HOOK
  chmod +x "$HOOK_PATH"

  log "Installed hook at $HOOK_PATH"
  "$INSTALLER_PATH" --sync
}

case "${1:-}" in
  ""|--install)
    install_hook
    ;;
  --sync)
    shift
    sync_heroic "$@"
    ;;
  -h|--help)
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
