#!/usr/bin/env bash
set -euo pipefail

INSTALLER_PATH="$HOME/.local/bin/install-omarchy-adwaita-for-steam-theme-sync.sh"
HOOK_DIR="$HOME/.config/omarchy/hooks/theme-set.d"
HOOK_PATH="$HOOK_DIR/sync-adwaita-for-steam.sh"
STEAM_THEME_DIR="${ADWAITA_FOR_STEAM_DIR:-$HOME/Adwaita-for-Steam}"
OMARCHY_COLORS="${OMARCHY_COLORS_FILE:-$HOME/.config/omarchy/current/theme/colors.toml}"
COLOR_THEME_NAME="${ADWAITA_FOR_STEAM_COLOR_THEME:-omarchy}"
COLOR_THEME_DIR="$STEAM_THEME_DIR/adwaita/colorthemes/$COLOR_THEME_NAME"
COLOR_THEME_CSS="$COLOR_THEME_DIR/$COLOR_THEME_NAME.css"

log() {
  printf 'omarchy-adwaita-for-steam-theme-sync: %s\n' "$*" >&2
}

usage() {
  cat <<'USAGE'
Usage:
  install-omarchy-adwaita-for-steam-theme-sync.sh          Install the Omarchy hook and sync Steam now
  install-omarchy-adwaita-for-steam-theme-sync.sh --sync   Sync Adwaita-for-Steam with the current Omarchy theme now

The hook runs after `omarchy theme set ...`, generates an Adwaita-for-Steam
`omarchy` color theme from ~/.config/omarchy/current/theme/colors.toml, and
runs Adwaita-for-Steam's installer with `--color-theme omarchy`.

Set ADWAITA_FOR_STEAM_DIR before running if Adwaita-for-Steam is somewhere
other than ~/Adwaita-for-Steam. Set ADWAITA_FOR_STEAM_SKIP_INSTALL=1 to only
generate the CSS file.
USAGE
}

die() {
  log "$*"
  exit 1
}

read_color() {
  local key="$1"
  local fallback="${2:-}"
  local value

  value="$(sed -nE "s/^[[:space:]]*$key[[:space:]]*=[[:space:]]*\"(#[0-9A-Fa-f]{6})\"[[:space:]]*$/\\1/p" "$OMARCHY_COLORS" | tail -n 1)"
  printf '%s\n' "${value:-$fallback}"
}

hex_to_rgb() {
  local hex="${1#'#'}"

  if [[ ! $hex =~ ^[0-9A-Fa-f]{6}$ ]]; then
    die "invalid color '$1'"
  fi

  printf '%d, %d, %d\n' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

mix_hex() {
  local base="${1#'#'}"
  local overlay="${2#'#'}"
  local overlay_percent="$3"
  local base_percent=$((100 - overlay_percent))
  local r g b

  if [[ ! $base =~ ^[0-9A-Fa-f]{6}$ || ! $overlay =~ ^[0-9A-Fa-f]{6}$ ]]; then
    die "invalid color mix '$1' '$2'"
  fi

  r=$(( (0x${base:0:2} * base_percent + 0x${overlay:0:2} * overlay_percent) / 100 ))
  g=$(( (0x${base:2:2} * base_percent + 0x${overlay:2:2} * overlay_percent) / 100 ))
  b=$(( (0x${base:4:2} * base_percent + 0x${overlay:4:2} * overlay_percent) / 100 ))

  printf '#%02x%02x%02x\n' "$r" "$g" "$b"
}

sync_adwaita_for_steam() {
  [[ -d $STEAM_THEME_DIR ]] || die "Adwaita-for-Steam directory not found: $STEAM_THEME_DIR"
  [[ -f $OMARCHY_COLORS ]] || die "Omarchy colors file not found: $OMARCHY_COLORS"

  local background foreground selection_foreground accent accent_bright
  local red red_bright green green_bright yellow yellow_bright cyan
  local black bright_black surface surface_strong surface_muted

  background="$(read_color background '#222226')"
  foreground="$(read_color foreground '#ffffff')"
  selection_foreground="$(read_color selection_foreground "$background")"
  accent="$(read_color accent "$(read_color color4 '#3584e4')")"
  accent_bright="$(read_color color12 "$accent")"
  red="$(read_color color1 '#c01c28')"
  red_bright="$(read_color color9 "$red")"
  green="$(read_color color2 '#26a269')"
  green_bright="$(read_color color10 "$green")"
  yellow="$(read_color color3 '#cd9309')"
  yellow_bright="$(read_color color11 "$yellow")"
  cyan="$(read_color color6 "$accent")"
  black="$(read_color color0 "$background")"
  bright_black="$(read_color color8 "$background")"
  surface="$(mix_hex "$background" "$foreground" 10)"
  surface_strong="$(mix_hex "$background" "$foreground" 14)"
  surface_muted="$(mix_hex "$background" "$foreground" 6)"

  mkdir -p "$COLOR_THEME_DIR"

  cat >"$COLOR_THEME_CSS" <<CSS
/*
 * Generated by install-omarchy-adwaita-for-steam-theme-sync.sh
 * Source: $OMARCHY_COLORS
 */

:root
{
	/* The main accent color and the matching text value */
	--adw-accent-bg-rgb: $(hex_to_rgb "$accent") !important;
	--adw-accent-fg-rgb: $(hex_to_rgb "$selection_foreground") !important;
	--adw-accent-rgb: $(hex_to_rgb "$accent_bright") !important;

	/* destructive-action buttons */
	--adw-destructive-bg-rgb: $(hex_to_rgb "$red") !important;
	--adw-destructive-fg-rgb: $(hex_to_rgb "$selection_foreground") !important;
	--adw-destructive-rgb: $(hex_to_rgb "$red_bright") !important;

	/* Levelbars, entries, labels and infobars. These don't need text colors */
	--adw-success-bg-rgb: $(hex_to_rgb "$green") !important;
	--adw-success-fg-rgb: $(hex_to_rgb "$selection_foreground") !important;
	--adw-success-rgb: $(hex_to_rgb "$green_bright") !important;

	--adw-warning-bg-rgb: $(hex_to_rgb "$yellow") !important;
	--adw-warning-fg-rgb: $(hex_to_rgb "$selection_foreground") !important;
	--adw-warning-fg-a: 0.8 !important;
	--adw-warning-rgb: $(hex_to_rgb "$yellow_bright") !important;

	--adw-error-bg-rgb: $(hex_to_rgb "$red") !important;
	--adw-error-fg-rgb: $(hex_to_rgb "$selection_foreground") !important;
	--adw-error-rgb: $(hex_to_rgb "$red_bright") !important;

	/* Window */
	--adw-window-bg-rgb: $(hex_to_rgb "$background") !important;
	--adw-window-fg-rgb: $(hex_to_rgb "$foreground") !important;

	/* Views - e.g. text view or tree view */
	--adw-view-bg-rgb: $(hex_to_rgb "$black") !important;
	--adw-view-fg-rgb: $(hex_to_rgb "$foreground") !important;

	/* Header bar, search bar, tab bar */
	--adw-headerbar-bg-rgb: $(hex_to_rgb "$surface") !important;
	--adw-headerbar-fg-rgb: $(hex_to_rgb "$foreground") !important;
	--adw-headerbar-border-rgb: $(hex_to_rgb "$surface_strong") !important;
	--adw-headerbar-backdrop-rgb: $(hex_to_rgb "$background") !important;
	--adw-headerbar-shade-rgb: $(hex_to_rgb "$black") !important;
	--adw-headerbar-shade-a: 0.36 !important;
	--adw-headerbar-darker-shade-rgb: $(hex_to_rgb "$black") !important;
	--adw-headerbar-darker-shade-a: 0.9 !important;

	/* Split pane views */
	--adw-sidebar-bg-rgb: $(hex_to_rgb "$surface") !important;
	--adw-sidebar-fg-rgb: $(hex_to_rgb "$foreground") !important;
	--adw-sidebar-backdrop-rgb: $(hex_to_rgb "$background") !important;
	--adw-sidebar-shade-rgb: $(hex_to_rgb "$black") !important;
	--adw-sidebar-shade-a: 0.25 !important;

	--adw-secondary-sidebar-bg-rgb: $(hex_to_rgb "$surface_muted") !important;
	--adw-secondary-sidebar-fg-rgb: $(hex_to_rgb "$foreground") !important;
	--adw-secondary-sidebar-backdrop-rgb: $(hex_to_rgb "$black") !important;
	--adw-secondary-sidebar-shade-rgb: $(hex_to_rgb "$black") !important;
	--adw-secondary-sidebar-shade-a: 0.25 !important;

	/* Cards, boxed lists */
	--adw-card-bg-rgb: $(hex_to_rgb "$foreground") !important;
	--adw-card-bg-a: 0.08 !important;
	--adw-card-fg-rgb: $(hex_to_rgb "$foreground") !important;
	--adw-card-shade-rgb: $(hex_to_rgb "$black") !important;
	--adw-card-shade-a: 0.36 !important;

	/* Dialogs */
	--adw-dialog-bg-rgb: $(hex_to_rgb "$surface_strong") !important;
	--adw-dialog-fg-rgb: $(hex_to_rgb "$foreground") !important;

	/* Popovers */
	--adw-popover-bg-rgb: $(hex_to_rgb "$surface_strong") !important;
	--adw-popover-fg-rgb: $(hex_to_rgb "$foreground") !important;
	--adw-popover-shade-rgb: $(hex_to_rgb "$black") !important;
	--adw-popover-shade-a: 0.25 !important;

	/* Banners */
	--adw-banner-bg-rgb: $(hex_to_rgb "$surface_strong") !important;
	--adw-banner-bg-a: 0.3 !important;
	--adw-banner-fg-rgb: $(hex_to_rgb "$foreground") !important;

	/* Thumbnails */
	--adw-thumbnail-bg-rgb: $(hex_to_rgb "$surface_strong") !important;
	--adw-thumbnail-fg-rgb: $(hex_to_rgb "$foreground") !important;

	/* Miscellaneous */
	--adw-shade-rgb: $(hex_to_rgb "$black") !important;
	--adw-shade-a: 0.25 !important;

	/* Skin-specific */
	--adw-user-offline-rgb: $(hex_to_rgb "$bright_black") !important;
	--adw-user-online-rgb: $(hex_to_rgb "$cyan") !important;
	--adw-user-ingame-rgb: $(hex_to_rgb "$green_bright") !important;
}
CSS

  if [[ ${ADWAITA_FOR_STEAM_SKIP_INSTALL:-0} == 1 ]]; then
    log "Generated $COLOR_THEME_CSS"
    return 0
  fi

  (
    cd "$STEAM_THEME_DIR"
    ./install.py --color-theme "$COLOR_THEME_NAME" ${ADWAITA_FOR_STEAM_INSTALL_ARGS:-}
  )
}

install_hook() {
  local source_path target_path

  mkdir -p "$HOME/.local/bin" "$HOOK_DIR"

  source_path=$(realpath -m "${BASH_SOURCE[0]}")
  target_path=$(realpath -m "$INSTALLER_PATH")
  if [[ "$source_path" != "$target_path" ]]; then
    cp "$source_path" "$INSTALLER_PATH"
  fi
  chmod +x "$INSTALLER_PATH"

  printf '%s\n' \
    '#!/usr/bin/env bash' \
    'exec "$HOME/.local/bin/install-omarchy-adwaita-for-steam-theme-sync.sh" --sync "$@"' \
    >"$HOOK_PATH"
  chmod +x "$HOOK_PATH"

  log "Installed hook at $HOOK_PATH"
  "$INSTALLER_PATH" --sync
}

case "${1:-}" in
  ""|--install)
    install_hook
    ;;
  --sync)
    shift
    sync_adwaita_for_steam "$@"
    ;;
  -h|--help)
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
