# Extra env variables
# env = MY_GLOBAL_ENV,setting

env = WEBKIT_DISABLE_DMABUF_RENDERER,1
env = GSK_RENDERER,gl

# Window Rules

windowrule = workspace 2, match:class (discord|vesktop|steam|heroic)
windowrule = workspace 3, match:class (outlook-for-linux)
windowrule = workspace 4, match:class (teams-for-linux)
windowrule = workspace 5, match:class (chrome-access.brivo.com__users-Default)
windowrule = workspace 6, match:class (feishin|chrome-patagonia-my.sharepoint.com___x__p_robert_tamayo_IQAwR0fqj7tFQZcqBzTOPy5wAVOljM8P_eymaZDiDXel3ro-Default)
windowrule = workspace 7, match:class (com.github.iwalton3.jellyfin-media-player|chrome-dashboard.envoy.com__visitors_entries-Default)
windowrule = workspace 9, match:class (parsecd|xfreerdp|com.moonlight_stream.Moonlight)