$terminal = uwsm app -- $TERMINAL
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$browser = omarchy-launch-browser

# Remove stupid Mac-style copy/paste / Tiling settings
unbind = SUPER SHIFT, V
unbind = SUPER, C
unbind = SUPER, V
bindd = SUPER, V, Toggle floating, togglefloating
bindd = SUPER SHIFT, O, Pop window out (float & pin), exec, omarchy-hyprland-window-pop
bindd = SUPER, J, Toggle window split, layoutmsg, togglesplit

# Control scratchpad
bindd = SUPER, grave, Toggle scratchpad, togglespecialworkspace, scratchpad
bindd = SUPER SHIFT, grave, Move window to scratchpad, movetoworkspacesilent, special:scratchpad

# Launch Applications
bindd = SUPER, return, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER, D, Discord, exec, uwsm app -- vesktop
bindd = SUPER, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, H, Heroic, exec, uwsm app -- heroic
bindd = SUPER, M, Gapless, exec, uwsm app -- gelly
bindd = SUPER, N, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER, S, Steam, exec, uwsm app -- steam
bindd = SUPER, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, C, Cava, exec, omarchy-launch-tui cava
bindd = SUPER SHIFT, J, Delfin, exec, uwsm app -- delfin
bindd = SUPER SHIFT, M, Youtube Music, exec, uwsm app -- youtube-music-desktop-app
bindd = SUPER SHIFT, R, Reset, exec, bash -lc 'hyprctl dispatch exit'
bindd = SUPER SHIFT, S, SublimeText, exec, uwsm app -- subl

#Launch webapps
# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER, A, T3, exec, omarchy-launch-or-focus-webapp "T3 Chat" "https://t3.chat"
bindd = SUPER, C, Notion Calendar, exec, omarchy-launch-or-focus-webapp "Notion Calendar" "https://calendar.notion.so/"
bindd = SUPER, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER, R, Reddit, exec, omarchy-launch-or-focus-webapp Reddit "https://reddit.com"
bindd = SUPER, X, Bluesky, exec, omarchy-launch-or-focus-webapp BlueSky "https://bsky.app"
bindd = SUPER, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"
bindd = SUPER SHIFT, G, Google Maps, exec, omarchy-launch-or-focus-webapp "Google Maps" "https://google.com/maps"
bindd = SUPER SHIFT, P, Photopea, exec, omarchy-launch-or-focus-webapp Photopea "https://photopea.com"
bindd = SUPER SHIFT, X, Monochrome, exec, omarchy-launch-or-focus-webapp Monochrome "https://monochrome.samidy.com/"

# Work
bindd = SUPER, E, Brivo, exec, omarchy-launch-or-focus-webapp Brivo "https://access.brivo.com/users"
bindd = SUPER SHIFT, E, Excel, exec, omarchy-launch-or-focus-webapp Excel "https://patagonia-my.sharepoint.com/:x:/p/robert_tamayo/IQAwR0fqj7tFQZcqBzTOPy5wAVOljM8P_eymaZDiDXel3ro?e=77in6w&wdOrigin=TEAMS-WEB.null_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1773176758807&web=1"
bindd = SHIFT ALT, E, Envoy, exec, omarchy-launch-or-focus-webapp Envoy "https://dashboard.envoy.com/visitors/entries"
IQAwR0fqj7tFQZcqBzTOPy5wAVOljM8P_eymaZDiDXel3ro?e=77in6w&wdOrigin=TEAMS-WEB.null_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1773089809241&web=1"
bindd = SUPER SHIFT, O, Outlook, exec, /opt/outlook-for-linux/outlook-for-linux %U
bindd = SUPER SHIFT, T, Teams, exec, /opt/teams-for-linux/teams-for-linux %UV


# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

